############################
## Navbar
############################

main:
# - name: Home
#   url: /
#   weight: 10
- name: About
  url: /about/
  weight: 20
- name: Tech
  url: /tech/
  weight: 40
- name: Blog
  url: /blog/
  weight: 50